spring.application.name=currency-service
<<<<<<< HEAD
=======

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

info.app.name=${spring.application.name}

info.app.description=Servi�o de "troca" de moeda

info.app.autor=Isadora Aguirre Dal Conte

eureka.instance.metadata-map.github.repo=isaguirredc/microservices-java-202601

spring.cloud.openfeign.client.config.default.connect-timeout=1000

spring.cloud.openfeign.client.config.default.read-timeout=3000

resilience4j.retry.instances.bcbRetry.max-attempts=3

resilience4j.retry.instances.bcbRetry.wait-duration=500ms

resilience4j.retry.instances.bcbRetry.enable-exponential-backoff=true

resilience4j.retry.instances.bcbRetry.exponential-backoff-multiplier=2

resilience4j.retry.instances.bcbRetry.enable-randomized-wait=true

spring.cache.type=caffeine

spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15s

spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.instances.bcbCB.sliding-window-size=10

resilience4j.circuitbreaker.instances.bcbCB.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.bcbCB.wait-duration-in-open-state=30s

resilience4j.circuitbreaker.instances.bcbCB.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.bcbCB.automatic-transition-from-open-to-half-open-enabled=true

management.health.circuitbreakers.enabled=true

spring.cloud.openfeign.circuitbreaker.group.enabled=true
>>>>>>> 63fd536 (última atualização)
