spring.application.name=greeting-service
<<<<<<< HEAD
=======

>>>>>>> 63fd536 (última atualização)
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

<<<<<<< HEAD
spring.profiles.active=es
=======
spring.profiles.active=es

spring.config.import=optional:configserver:http://localhost:8888/

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuitbreakerevents

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

info.app.name=${spring.application.name}

info.app.description=Servi�o de sauda��o

info.app.autor=Isadora Aguirre Dal Conte

eureka.instance.metadata-map.github.repo=isaguirredc/microservices-java-202601
>>>>>>> 63fd536 (última atualização)
